name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Fix held packages and update system
      run: |
        sudo apt-get update
        sudo apt-get install -y --allow-downgrades --allow-remove-essential --allow-change-held-packages \
          apt-transport-https ca-certificates curl software-properties-common
        sudo apt-get remove -y containerd
        sudo apt-get autoremove -y
        sudo apt-get clean

    - name: Install Docker
      run: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
        echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        sudo apt-get update
        sudo apt-get install -y docker-ce docker-ce-cli containerd.io

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag web_viewer:$(date +%s)

    - name: Push the Docker image
      run: docker push web_viewer:$(date +%s)
